src/Geo/AppBundle/Entity/Ticket.php
<?php

namespace Geo\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Geo\UserBundle\Entity\User;

class Ticket
{
    private $id;
    private $startDraw;
    private $endDraw;
    private $createdAt;
    private $ticketDetail;

    private $currentDraw;

    private $draws;

    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function setStartDraw($startDraw)
    {
        $this->startDraw = $startDraw;

        return $this;
    }

    public function getStartDraw()
    {
        return $this->startDraw;
    }

    public function setEndDraw($endDraw)
    {
        $this->endDraw = $endDraw;

        return $this;
    }

    public function getEndDraw()
    {
        return $this->endDraw;
    }

    public function setDraws($draws){
        $this->draws = $draws;

        return $this;
    }

    public function getEarnings()
    {
        foreach ($this->ticketDetail as $_ticketDetail) {
            $_ticketDetailNumbersSliced[] = $this->sliceColumn($_ticketDetail->getNumbers());
        }
        $earnings = 0;
        foreach ($this->draws as $draw) {
            $_numbers = $this->sliceColumn($draw->getNumbers());
            $_results = array();
            foreach ($_ticketDetailNumbersSliced as $_slice) {
                $_results[] = $this->compareColumns($_numbers, $_slice);
            }
            $draw->setResults($_results);
            $earnings += $draw->getEarnings();
        }

        return $earnings;
    }

    public function setCurrentDraw($currentDraw){
        $this->currentDraw = $currentDraw;
    }

    public function getCompletion()
    {
        if(!$this->currentDraw){
            return 0;
        }

        $_startDraw = $this->getStartDraw();
        $_endDraw = $this->getEndDraw();
        if ($_startDraw == $_endDraw) {
            $_completion = ($_endDraw == $this->currentDraw) ? 1 : 0;
        } else {
            $_pc = ($this->currentDraw - $_startDraw) / ($_endDraw - $_startDraw);
            $_completion = min(1, $_pc);
        }

        return $_completion;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setTicketDetail(\Geo\AppBundle\Entity\TicketDetail $ticketDetail = null)
    {
        $this->ticketDetail = $ticketDetail;

        return $this;
    }

    public function getTicketDetail()
    {
        return $this->ticketDetail;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getUser()
    {
        return $this->user;
    }

    private function sliceColumn($column)
    {
        //var_dump($column);
        $numbers = array_slice($column, 0, 5);
        sort($numbers);
        $joker = $column[5];
        return array("n" => $numbers, "j" => $joker);
    }

    private function compareColumns($drawColumn, $ticketColumn)
    {
        $res = array();
        foreach ($ticketColumn["n"] as $_ticketNumber) {
            $item["status"] = in_array($_ticketNumber, $drawColumn["n"]);
            $item["value"] = $_ticketNumber;
            $res[] = $item;
        }
        $item["status"] = ($ticketColumn["j"] == $drawColumn["j"]);
        $item["value"] = $ticketColumn["j"];
        $res[] = $item;
        return $res;
    }
}

src/Geo/AppBundle/Controller/MainController.php
<?php
namespace Geo\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Geo\AppBundle\Entity\Ticket;
use Geo\AppBundle\Entity\TicketDetail;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Finder\Exception\AccessDeniedException;

use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Helper\ProgressBar;

class MainController extends Controller
{

    /**
     * @Route("/", name="Tickets")
     * @Template()
     */
    public function mainAction()
    {
        $draw = $this->getCurrentDraw();

        $tickets = $this->getDoctrine()
            ->getRepository("GeoAppBundle:Ticket")
            ->findBy(array(
                "user" => $this->get('security.token_storage')->getToken()->getUser()
            ), array('createdAt' => 'DESC'));

        foreach ($tickets as $ticket) {

            $draws = $this->getDoctrine()
                ->getRepository("GeoAppBundle:Draw")
                ->createQueryBuilder('p')
                ->where('p.code >= :startDraw')
                ->andWhere('p.code <= :endDraw')
                ->setParameter('startDraw', $ticket->getStartDraw())
                ->setParameter('endDraw', $ticket->getEndDraw())
                ->orderBy('p.code', 'DESC')
                ->getQuery()
                ->getResult();

            $ticket->setDraws($draws);
            $ticket->setCurrentDraw($draw->getCode());
        }

        return array(
            "tickets" => $tickets,
            "draw" => $draw,
            "greeting" => $this->getGreetingMsg(),
        );
    }

    /**
     * @Route("/ticket/read/{id}", name="Ticket")
     * @Template()
     */
    public function ticketAction($id)
    {
        $ticket = $this->getDoctrine()
            ->getRepository("GeoAppBundle:Ticket")
            ->findOneById($id);

        $draws = $this->getDoctrine()
            ->getRepository("GeoAppBundle:Draw")
            ->createQueryBuilder('p')
            ->where('p.code >= :startDraw')
            ->andWhere('p.code <= :endDraw')
            ->setParameter('startDraw', $ticket->getStartDraw())
            ->setParameter('endDraw', $ticket->getEndDraw())
            ->orderBy('p.code', 'DESC')
            ->getQuery()
            ->getResult();

        $ticket->setDraws($draws);
        $ticket->setCurrentDraw($this->getCurrentDraw()->getCode());

        return array(
            "ticket" => $ticket,
            "draws" => $draws,
        );
    }

    /**
     * @Route("/ticket/create", defaults={"id" = false})
     * @Route("/ticket/update/{id}")
     * @Template()
     */
    public function ticketFormAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $ticket = new Ticket;
        if ($id) {
            $ticket = $em->getRepository("GeoAppBundle:Ticket")->findOneById($id);
            if ($ticket->getuser() != $this->get('security.token_storage')->getToken()->getUser()) {
                throw new AccessDeniedException();
            }
        }
        return array(
            "ticket" => $ticket,
        );
    }

    /**
     * @Route("/ticket/delete/{id}")
     */
    public function ticketDeleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $ticket = $em->getRepository("GeoAppBundle:Ticket")->findOneById($id);
        if ($ticket->getuser() != $this->get('security.token_storage')->getToken()->getUser()) {
            throw new AccessDeniedException();
        }
        $em->remove($ticket);
        $em->flush();

        return $this->redirect("/");
    }

    /**
     * @Route("/ticketsave")
     */
    public function ticketSaveAction(Request $request)
    {

        $em = $this->getDoctrine()->getManager();

        $_ticket_id = $request->get("ticket_id");
        $_start_draw = $request->get("start_draw");
        $_end_draw = $request->get("end_draw");
        $_number = $request->get("number");

        if ($_ticket_id) {
            $ticket = $em->getRepository("GeoAppBundle:Ticket")->findOneById($_ticket_id);

            foreach ($ticket->getTicketDetail() as $_ticketDetail) {
                $em->remove($_ticketDetail);
            }
        } else {
            $ticket = new Ticket();
            $ticket->setCreatedAt(new \DateTime());
            $ticket->setUser($this->get('security.token_storage')->getToken()->getUser());
        }

        $ticket->setStartDraw($_start_draw);
        $ticket->setEndDraw($_end_draw);
        $em->persist($ticket);

        foreach ($_number as $col => $iter) {
            if (count(array_filter($iter)) == count($iter)) {
                $detail = new TicketDetail();
                $detail->setNumbers(array_values($iter));
                $detail->setTicket($ticket);
                $em->persist($detail);
            }
        }
        $em->flush();
        $response = new JsonResponse();
        return $response;
    }

    /**
     * @Route("/cron")
     */
    public function cronAction()
    {
        $fetch_service = $this->get("fetch");
        $fetch_service->fetch();
        return new JsonResponse($fetch_service->log);
    }

    //Helper functions

    private function getCurrentDraw()
    {
        return $this->getDoctrine()
            ->getRepository("GeoAppBundle:Draw")
            ->findOneBy(array(), array('code' => 'DESC'));

    }

    private function getGreetingMsg()
    {

        $msg = false;

        $greetings = array(
            "6" => "Mornin' Sunshine",
            "12" => "Good morning",
            "14" => "Good day",
            "17" => "Hello!!",
            "19" => "Good afternoon",
            "21" => "Good evening",
            "23" => "Go to bed...",
        );

        foreach ($greetings as $_time => $_msg) {
            if (date("G") <= $_time) {
                $msg = $_msg;
                break;
            }
        }

        return $msg;
    }
}

src/Geo/AppBundle/Resources/views/Main/main.html.twig
{% extends "GeoAppBundle::base.html.twig" %}

{% block title %}
    Tickets
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(function () {

            function fetch_ticket(ticket_id, anchor) {
                $("html, body").animate({scrollTop: 0}, "slow");
                $("#ticket").addClass("loading");
                $(".ui.loading.segment:after").css("top", "150px");
                $(anchor).siblings().removeClass("active");
                $(anchor).addClass("active");
                $("#ticket").load("ticket/read/" + ticket_id, function () {
                    $("#ticket").removeClass("loading");
                })
            }

            $('.ticket').on("click", function () {
                fetch_ticket($(this).data("id"), $(this))
            })

            if ($(".ticket").first().length) {
                fetch_ticket($(".ticket").first().data("id"), $(".ticket").first());
            }
        })
    </script>
{% endblock %}

{% block content %}
    <div class="ui grid">
        {% if tickets|length %}
            <div class="five wide column">
                <div class="ui vertical pointing fluid menu">
                    <a href="/ticket/create" class="item amodal">
                        <strong><i class="add icon"></i> Add New Ticket</strong>
                    </a>
                    {% for ticket in tickets %}
                        <a class="item ticket" data-id="{{ ticket.id }}">
                            <div class="ui label {{ ticket.earnings or ticket.earnings == -1 ? 'green' : '' }} }}">
                                {{ ticket.earnings == -1 ? "SUPER<br>WIN!!!" : [ticket.earnings|number_format(2),"&euro;"]|join|raw }}
                            </div>
                            {{ ticket.startDraw }} - {{ ticket.endDraw }}<br>
                            <small>{{ ticket.createdAt|date("d/m/Y") }} | {{ (ticket.completion * 100) | round  }}%</small>
                        </a>
                    {% endfor %}
                </div>
                <div class="ui blue segment">
                    <h4 class="ui header">Latest Draw</h4>

                    <div class="ui statistic fluid" style="width: 100%;">
                        <div class="value" style="color: #666;">
                            {{ draw.code }}
                        </div>
                        <div class="label">
                            {{ draw.drawAt|date("d/m/Y") }}
                        </div>
                    </div>
                    <div class="ui tiny circular labels numbers">
                        {% for number in draw.numbers %}
                            <span class="ui label">{{ number }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="eleven wide column">
                <div id="ticket" class="ui segment" style="min-height: 200px;padding: 0;"></div>
            </div>
        {% else %}
            <div class="three wide column"></div>
            <div class="ten wide column">
                <div class="ui piled segment" style="margin-top: 50px;">
                    <h3 class="ui header">Welcome <strong>{{ app.user.username|title }}</strong> to JokerBot!</h3>
                    <h4>A few things to keep in mind</h4>

                    <p>This is just a fun project of me. I created it just to play with some web techologies.</p>

                    <p>However, this it is a working service, which I use for my personal tickets, and I actively
                        improving.</p>

                    <p>It's is very likely to issues may occure here or there and if so please give me feedback in order
                        to fix them.</p>

                    <p><strong>Also it is VERY IMPORTANT, ALWAYS to validate your ticket in your agent. This service may
                            NOT give you correct results all the time.</strong></p>

                    <p>Finaly this service is based on data provided by OPAP Web Service. That service somtimes lags and
                        doesn't responed correctly. When that happens draw results will not be available</p>

                    <div class="ui divider"></div>

                    <p>So... ready to create your first ticket???. Click bellow...</p>
                    <a href="ticketform" class="ui button green fluid amodal">Add your first Ticket</a>

                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

src/Geo/AppBundle/Resources/views/Main/ticket.html.twig
<script type="text/javascript">
    $(function () {
        $('.ui.accordion').accordion();
        $('.ui.dropdown').dropdown();
    })
</script>
<div class="ui top attached tertiary segment" style="margin-top:0">

    <div class="ui icon top left pointing dropdown">
        <i class="icon bars"></i>

        <div class="menu">
            <a href="/ticket/update/{{ ticket.id }}" class="item amodal"><i class="icon pencil"></i> Edit</a>
            <a href="/ticket/delete/{{ ticket.id }}" class="item"><i class="icon remove"></i> Delete</a>
        </div>
    </div>

    <div class="ui divided horizontal list">
        <div class="item"><strong>{{ ticket.createdAt|date("d/m/Y") }}</strong></div>
        <div class="item"><strong>{{ ticket.startDraw }} - {{ ticket.endDraw }}</strong></div>
        <div class="item">
            <strong>{{ ticket.earnings == -1 ? "SUPER WIN!!!" : [ticket.earnings|number_format(2),"&euro;"]|join|raw }}</strong>
        </div>
        <div class="item"><strong>{{ (ticket.completion * 100) | round }}%</strong></div>
    </div>

</div>
<div class="ui tall stacked attached segment">
    <div class="ui grid">
        {% for draw in draws %}
            <div class="six wide column">
                <div class="ui statistic fluid" style="width: 100%;">
                    <div class="value" style="color: #666;">
                        {{ draw.code }}
                    </div>
                    <div class="label">
                        {{ draw.drawAt|date("d/m/Y") }}
                    </div>
                </div>
                <div class="ui tiny circular labels numbers">
                    {% for number in draw.numbers %}
                        <span class="ui label">{{ number }}</span>
                    {% endfor %}
                </div>
                {% if draw.earnings == -1 %}
                    <span style="margin-top:10px;" class="ui red circular huge fluid label">SUPER WIN!!!</span>
                {% elseif draw.earnings > 0 %}
                    <span style="margin-top:10px;"
                          class="ui green circular huge fluid label">+ {{ draw.earnings|number_format(2, '.', ',') }} &euro;</span>
                {% endif %}
            </div>
            <div class="ten wide column">
                {% for result in draw.results %}
                    <div class="ui large circular labels numbers">
                        {% for number in result %}
                            <span class="ui {% if number.status %}green{% endif %} label">{{ number.value }}</span>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            {% if loop.last == false %}
                <div class="ui divider"></div>
            {% endif %}

        {% else %}
            <div class="column" style="min-height: 200px;">
                <div class="ui icon message">
                    <i class="icon frown"></i>

                    <div class="content">
                        <div class="header">No draws where found</div>
                        <p>Please check back soon.</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

src/Geo/AppBundle/Resources/views/Main/ticketForm.html.twig
<form id="form-ticket" action="ticketsave" class="ui small modal">

    <i class="close icon"></i>

    <div class="header">
        {% if ticket.id is defined %}
            Edit Ticket
        {% else %}
            Add new Ticket - {{ ticket.createdAt|date("d/m/Y") }}
        {% endif %}
    </div>

    <div class="ui form content">
        <input class="" type="hidden" name="ticket_id" value="{{ ticket.id|default('') }}">

        <div class="ui horizontal divider" style="margin-top: 0;">
            Draws
        </div>

        <div class="two fields">
            <div class="field">
                <label>From</label>
                <input class="draw-range" type="text" name="start_draw" value="{{ ticket.startDraw|default('') }}">
            </div>
            <div class="field">
                <label>To</label>
                <input class="draw-range" type="text" name="end_draw" value="{{ ticket.endDraw|default('') }}">
            </div>
        </div>


        <div class="ui horizontal divider">
            Columns
        </div>

        {% for i in 0..4 %}
            <div class="seven fields jokernumbers">
                <div class="field">
                    <label>{{ i+1 }}.</label>
                </div>
                {% for j in 0..4 %}
                    <div class="field">
                        <input class="jokernumber" type="text" name="number[{{ i }}][{{ j }}]"
                               value="{{ ticket.ticketDetail[i].numbers[j]|default('') }}">
                    </div>
                {% endfor %}
                <div class="field">
                    <input class="jokernumber" type="text" name="number[{{ i }}][5]"
                           value="{{ ticket.ticketDetail[i].numbers[5]|default('') }}">
                </div>
            </div>
        {% endfor %}

    </div>

    <div class="actions">
        <button type="submit" class="ui green button ok">
            <i class="icon checkmark"></i>
            Save Ticket
        </button>
    </div>

    <script src="{{ asset('bundles/geoapp/plugins/jquery-autotab/js/jquery.autotab.min.js') }}"></script>

    <script type="text/javascript">
        $(function () {
            $('.draw-range').autotab({
                format:"number",
                maxlength: 4
            });
            $('.jokernumber').autotab({
                format:"number",
                maxlength: 2
            });
        })
    </script>
</form>